export const FETCH_PRODUCTS_ALL = 'FETCH_PRODUCTS_ALL';
export const FETCH_PRODUCTS_TECH = 'FETCH_PRODUCTS_TECH';
export const FETCH_PRODUCTS_CLOTHES = 'FETCH_PRODUCTS_CLOTHES';
// export const FETCH_CURRENCIES = 'GET_CURRENCIES';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';